---
- name: Install Node Exporter
  become: true
  apt:
    name: prometheus-node-exporter
    state: present

- name: Install Prometheus
  become: true
  apt:
    name: prometheus
    state: present

- name: Start and enable Prometheus service
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: true

- name: Start prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true


- name: Install Telegraf on all hosts
  become: true
  apt:
    name: telegraf
    state: present


- name: Copy telegraf.conf to /etc/telegraf/telegraf.conf
  become: true
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'

- name: Start and enable Telegraf service on all hosts
  become: true
  systemd:
    name: telegraf
    state: started
    enabled: true