---
- name: Install Node Exporter
  become: true
  apt:
    name: prometheus-node-exporter
    state: present

- name: Install Prometheus
  become: true
  apt:
    name: prometheus
    state: present

- name: Start and enable Prometheus service
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: true

- name: Kill existing node_exporter process
  command: kill $(pgrep node_exporter)
  ignore_errors: true  # In case node_exporter isn't running

- name: Start prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true