prowlarr-dependency:
  global: {}

  image:
    repository: ghcr.io/k8s-at-home/prowlarr
    tag: v0.3.0.1710
    pullPolicy: IfNotPresent

  env:
    TZ: "Europe/London"
    PUID: "1003"
    PGID: "1003"

  podSecurityContext:
    runAsUser: 1003
    runAsGroup: 1003
    fsGroup: 1003

  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "chown -R 1003:1003 /config"]
      volumeMounts:
        - name: config
          mountPath: /config

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
      hosts:
        - host: "prowlarr.neilwylie.com"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "prowlarr.neilwylie.com"
          secretName: "prowlarr-tls-secret"

  persistence:
    config:
      enabled: true
      existingClaim: nfs-configs-pvc # Assuming this PVC is suitable for Prowlarr config
      # mountPath: /config # Default mount path for config, usually not needed to specify

  service:
    main:
      ports:
        http:
          port: 9696 # Default Prowlarr port