apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd # Lives in argocd namespace
  labels:
    category: monitoring-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.5.0 # Chart version from helm list
    helm:
      values: |
        grafana:
          additionalDataSources:
          - name: loki
            type: loki
            url: http://loki.observability.svc.cluster.local:3100
          - name: tempo
            type: tempo
            url: http://tempo.observability.svc.cluster.local:3100
        kubeControllerManager:
          endpoints:
          - 192.168.1.130
          - 192.168.1.153
          - 192.168.2.144
        kubeScheduler:
          endpoints:
          - 192.168.1.130
          - 192.168.1.153
          - 192.168.2.144

  destination:
    server: https://kubernetes.default.svc
    namespace: observability # Deploys to observability namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true