apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin # Name of this child application in ArgoCD
  namespace: argocd # This Application CR itself lives in 'argocd'
  labels:
    category: media-app # For grouping/filtering in ArgoCD UI/CLI
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Neilrw86/Nas-Automation
    targetRevision: June
    path: helm_charts/jellyfin # Path to your Jellyfin wrapper Helm chart
    helm:
      valueFiles:
        - Values.yaml # Use Values.yaml from helm_charts/jellyfin/

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Jellyfin's resources will be deployed into the 'default' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensures 'default' namespace exists