apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr # Name of this child application in ArgoCD
  namespace: argocd # This Application CR itself lives in 'argocd'
  labels:
    category: media-app # For grouping/filtering
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Neilrw86/Nas-Automation # Assuming this is the repo where the chart is
    targetRevision: main # Or the branch you are working on
    path: helm_charts/overseerr # Path to your Overseerr wrapper Helm chart
    helm:
      valueFiles:
        - values.yaml
      values: |
        overseerr-dependency:
          persistence:
            config:
              enabled: true
              size: 1Gi
              accessMode: ReadWriteOnce
              storageClass: "nfs-client"

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Overseerr's resources will be deployed into the 'default' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
