apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr # Name of this child application in ArgoCD
  namespace: argocd # This Application CR itself lives in 'argocd'
  labels:
    category: media-app # For grouping/filtering
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: radarr
    targetRevision: 16.2.2 # Using k8s-at-home chart
    helm:
      values:
        global: {}

        controller:
          main:
            type: deployment

        image:
          repository: linuxserver/radarr
          pullPolicy: IfNotPresent
          tag: latest

        podSecurityContext:
          runAsUser: 1003
          runAsGroup: 1003

        service:
          main:
            ports:
              main:
                port: 7878

        ingress:
          main:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
            hosts:
              - host: "radarr.neilwylie.com"
                paths:
                  - path: "/"
                    pathType: Prefix
            tls:
              - hosts:
                  - "radarr.neilwylie.com"
                secretName: "radarr-tls-secret"

        persistence:
          config:
            enabled: true
            existingClaim: nfs-configs-pvc
          downloads:
            enabled: true
            existingClaim: nfs-temp-pvc
            mountPath: /downloads
          movies:
            enabled: true
            existingClaim: nfs-films-pvc
            mountPath: /movies

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Radarr's resources will be deployed into the 'default' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
