---
    - name: workstation base packages 
      become: yes
      apt:
        update_cache: yes
        name:
          - nmap
          - neovim
          - netcat-openbsd
          - curl
          - net-tools
          - lsof
          - syslog-ng
          - vim
          - terminator
        state: present
