---
  - name: base hypervisor packages
    become: yes
    apt:
      name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - python-libvirt
      - python-lxml
      - bridge-utils
      - cloud-image-utils
      - virtinst
      state: present

  - name: enable libvirtd on boot
    become: yes
    service:
        name: libvirtd
        enabled: true
        state: started


- name: Virtual machine directory
  file:
    path: /virt/vms
    state: directory
    owner: root
    group: root
    mode: 0755
