apiVersion: v1
kind: Service
metadata:
  name: {{ include "media.fullname" . }}-couchpotato
spec:
  selector:
    app.kubernetes.io/name: couchpotato
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
