apiVersion: v2
name: openwebui-wrapper # Renaming to clarify it's a wrapper
description: A wrapper Helm chart to deploy OpenWebUI from the official chart with custom values.
type: application
version: 0.1.0 # Version of this chart
appVersion: "0.6.13" # The version of OpenWebUI app this chart aims to deploy

dependencies:
  - name: open-webui # The name of the chart in the open-webui repository
    # IMPORTANT: Use the CHART VERSION you want
    version: "6.19.0"
    repository: "https://helm.openwebui.com/"