# Example content for helm_charts/openwebui/values.yaml
replicaCount: 1

image:
  repository: ghcr.io/open-webui/open-webui
  pullPolicy: IfNotPresent
  tag: "main"

service:
  type: ClusterIP
  port: 3030      # Service port
  targetPort: 8080 # Container port for OpenWebUI

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-cfdns"
  hosts:
    - host: "ollama.neilwylie.com" # Your desired hostname for OpenWebUI
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: openwebui-service-tls
      hosts:
        - "ollama.neilwylie.com"

# Add other values as needed, e.g., resources, serviceAccount
