---
# shared role for establishing base-config and packages
- name:  Install required packages
  anisble.builtin.package:
    name:
      - curl
      - jwhois
      - net-tools
    state: present
    become: yes


- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts
  become: yes
