---
  - name: shared base packages 
    become: yes
    apt:
      update_cache: yes
      name:
        - nmap
        - neovim
        - netcat-openbsd
        - curl
        - net-tools
        - lsof
        - syslog-ng
        - vim
      state: present

  - name: create the ansible user account
    user: name=ansible append=yes state=present createhome=yes shell=/bin/bash

  - name: allow 'ansible' to use sudo without needing a password
    lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


  - name: Set authorized key taken from file
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Copy .bash_aliases
    become: yes 
    copy:
      src: bash_aliases
      dest: /etc/profile.d/00-bash_aliases.sh
      owner: neil
      group: neil
      mode: 0644

