apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # You can name this whatever you like, e.g., "root-apps", "app-of-apps", "cluster-applications"
  name: my-nas-automation-apps
  namespace: argocd # This application CR itself lives in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Or your specific Argo CD project

  source:
    # !!! IMPORTANT: Replace with your actual Git repo URL !!!
    repoURL: "https://github.com/Neilrw86/Nas-Automation.git"
    # This is the path it will monitor for other Application manifests
    path: argocd-apps
    targetRevision: HEAD # Or your main branch, e.g., 'main'

    # If you want Argo CD to look for *.yaml files in subdirectories of argocd-apps/
    # directory:
    #   recurse: true

  destination:
    # The Application CRs found in 'argocd-apps/' path will be created
    # in the cluster where Argo CD is running.
    server: https://kubernetes.default.svc
    # The Application CRs themselves are created in the 'argocd' namespace.
    # The individual apps defined in argocd-apps/ (like jellyfin-app.yaml)
    # will specify their own destination.namespace for their workloads.
    namespace: argocd

  syncPolicy:
    automated:
      prune: true    # If you delete an app's YAML from argocd-apps/, Argo CD will delete the app
      selfHeal: true # If the app definition in Argo CD drifts, it will be corrected
    # It's generally not needed to CreateNamespace=true here, as 'argocd' namespace must exist.