apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-couchpotato
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: couchpotato
  template:
    metadata:
      labels:
        app.kubernetes.io/name: couchpotato
    spec:
      containers:
      - name: couchpotato
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5050
        env:
        - name: PUID
          value: "{{ .Values.puid }}"
        - name: PGID
          value: "{{ .Values.pgid }}"
        volumeMounts:
        - name: couchpotato-config
          mountPath: /config
          subPath: couchpotato
        - name: temp-downloads
          mountPath: /downloads
        - name: movies
          mountPath: /movies
      volumes:
      - name: couchpotato-config
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaims.config }}
      - name: temp-downloads
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaims.downloads }}
      - name: movies
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaims.movies }}