apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-couchpotato
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "couchpotato.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "couchpotato.labels" . | nindent 8 }}
    spec:
      containers:
      - name: couchpotato
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5050
        env:
        - name: PUID
          value: "{{ .Values.puid }}"
        - name: PGID
          value: "{{ .Values.pgid }}"
        volumeMounts:
        - name: couchpotato-config
          mountPath: /config
          subPath: couchpotato
        - name: temp-downloads
          mountPath: /downloads
        - name: movies
          mountPath: /movies
      volumes:
      - name: couchpotato-config
        persistentVolumeClaim:
          claimName: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "config") }}
      - name: temp-downloads
        persistentVolumeClaim:
          claimName: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "downloads") }}
      - name: movies
        persistentVolumeClaim:
          claimName: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "movies") }}
