apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-couchpotato
spec:
  selector:
    app.kubernetes.io/name: couchpotato
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}