apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-couchpotato
  labels:
    {{- include "couchpotato.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "couchpotato.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
