---
  - name: add google chrome repo to workstations
    become: yes
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: add nordvpn repo to workstations
    become: yes
    ansible.builtin.apt_repository:
      repo: deb https://repo.nordvpn.com//deb/nordvpn/debian stable main
      state: present



  - name: workstation base packages
    become: yes
    apt:
      update_cache: yes
      name:
        - terminator
        - ansible
        - google-chrome-stable
        - net-base
        - tcpdump
        - atop
        - htop
        - nordvpn
        - vim.tiny
      state: present

