---
- name: add google chrome repo to workstations
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: add nordvpn repo to workstations
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://repo.nordvpn.com//deb/nordvpn/debian stable main
    state: present

- name: Add signal apt key 
  ansible.builtin.apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: add signal to all workstations
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: workstation base packages
  become: yes
  apt:
    update_cache: yes
    name:
      - terminator
      - ansible
      - google-chrome-stable
      - net-base
      - tcpdump

- name: Install kubectl using snap
  become: yes
  ansible.builtin.snap:
    name: kubectl
    classic: yes
    state: present