# This values.yaml is for your 'lazylibrarian-wrapper' chart.
# All configurations for the actual Lazylibrarian deployment will be under 'lazylibrarian-dependency'
# (the alias defined in Chart.yaml for the k8s-at-home/lazylibrarian chart).

lazylibrarian-dependency:
  image:
    repository: "linuxserver/lazylibrarian"
    tag: "version-1152df82" # Or "latest"
    pullPolicy: "IfNotPresent"

  env:
    TZ: "Europe/London" # Adjust as needed
    PGID: "1003" # Adjust as needed
    PUID: "1003" # Adjust as needed

  service:
    main:
      ports:
        http:
          port: 5299 # Default port for Lazylibrarian

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod-cfdns" # Assuming this is your issuer
      hosts:
        - host: "lazylibrarian.neilwylie.com" # Adjust as needed
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "lazylibrarian.neilwylie.com" # Adjust as needed
          secretName: "lazylibrarian-tls" # Adjust as needed

  # This values.yaml is for your 'lazylibrarian-wrapper' chart.
# All configurations for the actual Lazylibrarian deployment will be under 'lazylibrarian-dependency'
# (the alias defined in Chart.yaml for the k8s-at-home/lazylibrarian chart).

lazylibrarian-dependency:
  image:
    repository: "linuxserver/lazylibrarian"
    tag: "version-1152df82" # Or "latest"
    pullPolicy: "IfNotPresent"

  env:
    TZ: "Europe/London" # Adjust as needed
    PGID: "1003" # Adjust as needed
    PUID: "1003" # Adjust as needed

  service:
    main:
      ports:
        http:
          port: 5299 # Default port for Lazylibrarian

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod-cfdns" # Assuming this is your issuer
      hosts:
        - host: "lazylibrarian.neilwylie.com" # Adjust as needed
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "lazylibrarian.neilwylie.com" # Adjust as needed
          secretName: "lazylibrarian-tls" # Adjust as needed

  persistence:
    config:
      enabled: true
      existingClaim: "nfs-configs-pvc"
      subPath: "lazylibrarian"
      mountPath: "/config" # Explicitly set mountPath

  extraVolumes: # This block is for additional volumes
    - name: books # Name of the volume
      persistentVolumeClaim:
        claimName: "nfs-books-pvc" # Your existing books PVC

  extraVolumeMounts: # This block is for mounting additional volumes
    - name: books # Must match the volume name
      mountPath: "/books" # Standard mount path for books in Lazylibrarian

  extraVolumes: # Add this block
    - name: books # Name of the volume
      persistentVolumeClaim:
        claimName: "nfs-books-pvc" # Your existing books PVC

  extraVolumeMounts: # Add this block
    - name: books # Must match the volume name
      mountPath: "/books" # Standard mount path for books in Lazylibrarian

  persistence:
    config:
      enabled: true
      existingClaim: "nfs-configs-pvc" # Use the general configs PVC
      subPath: "lazylibrarian" # Use subPath for Lazylibrarian's config
