---
- name: Add user "ansible" to remote server
  hosts: all
  remote_user: neil
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:

    - name: create the ansible user account
      user: name=ansible append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ansible' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ansible user
      authorized_key: user=ansible key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

