---
  - name: OS ubuntu update
    hosts: all
    gather_facts: yes
    tasks:
    - name: update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
    become: yes

  - name: OS centos update
    hosts: nas5
    gather_facts: yes
    tasks:
    - name: yum update all packages
      yum:
        name: '*'
        state: latest
    become: yes