apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  labels:
    category: utility-app
  namespace: argocd # Deploy this Application CR into the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Or your desired ArgoCD project

  source:
    repoURL: "https://github.com/Neilrw86/Nas-Automation.git" # Your Git repository URL
    path: helm_charts/kagent # Path to your new kagent wrapper chart
    targetRevision: July # Or your current working branch (e.g., main)
    helm:
      releaseName: kagent # This will be the Helm release name in the target namespace
      valueFiles:
        - values.yaml # Points to helm_charts/kagent/values.yaml in your repo
  destination:
    server: https://kubernetes.default.svc
    namespace: "kagent" # Changed to 'kagent' to match the original ingress setup and common practice

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensures the 'kagent' namespace is created