overseerr-dependency:
  global: {}

  image:
    repository: lscr.io/linuxserver/overseerr
    tag: latest
    pullPolicy: IfNotPresent

  env:
    TZ: "Europe/London"
    PUID: "1003"
    PGID: "1003"

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
      hosts:
        - host: "overseerr.neilwylie.com"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "overseerr.neilwylie.com"
          secretName: "overseerr-tls-secret"

  persistence:
    config:
      enabled: true
      existingClaim: nfs-configs-pvc # Assuming this PVC is suitable for Overseerr config
      subPath: overseerr # Subpath for Overseerr config

  service:
    main:
      ports:
        http:
          port: 5055 # Default Overseerr port