overseerr-dependency:
  global: {}

  # An initContainer is used to fix permissions on the subPath volume mount,
  # which is a common workaround for NFS volumes where fsGroup is not applied correctly.
  initContainers:
    fix-permissions:
      # Pinning to a specific digest ensures reproducible builds
      image: busybox:1.36.1@sha256:31f3955f475e40c62c6d4209f09fd9738cf6cadfc0f4aa76ba2d4d86f061c5b5
      command: ["sh", "-c", "chmod -R g+w /config"]
      volumeMounts:
        - name: config
          mountPath: /config
  # This security context is crucial for NFS with subPath.
  # It ensures the mounted /config directory is owned by the correct group.
  podSecurityContext:
    runAsUser: 1003
    fsGroup: 1003

  image:
    repository: lscr.io/linuxserver/overseerr
    tag: latest
    pullPolicy: IfNotPresent

  env:
    TZ: "Europe/London"
    PUID: "1003"
    PGID: "1003"

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
      hosts:
        - host: "overseerr.neilwylie.com"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "overseerr.neilwylie.com"
          secretName: "overseerr-tls-secret"

  persistence:
    config:
      enabled: true
      existingClaim: nfs-configs-pvc # Revert to your shared PVC
      subPath: overseerr # Isolate this app's data within the shared PVC

  service:
    main:
      ports:
        http:
          port: 5055 # Default Overseerr port