apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-sabnzb
spec:
  selector:
    app.kubernetes.io/name: sabnzb
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
  - protocol: TCP
    port: 8085
    targetPort: 8085
  - protocol: TCP
    port: 9090
    targetPort: 9090
  - protocol: TCP
    port: 9095
    targetPort: 9095