apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: "1003"
        - name: PGID
          value: "1003"
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: sonarr-config
          mountPath: /config
        - name: temp-downloads
          mountPath: /downloads
      volumes:
      - name: tv
        persistentVolumeClaim:
          claimName: nfs-tv-pvc
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-pvc
      - name: temp-downloads
        persistentVolumeClaim:
          claimName: temp-pvc