apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc  # Match the claimName in values.yaml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi   # Adjust this based on Homer's storage needs
  storageClassName: nas5-nfs-storage
