apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-configs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 246Gi
  volumeName: nfs-configs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-films-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Ti
  volumeName: nfs-films-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tv-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9Ti
  volumeName: nfs-tv-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-temp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi  # Adjust to match the PV capacity
  volumeName: nfs-temp-pv