apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas5-nfs-storage  # Choose a descriptive name
provisioner: kubernetes.io/nfs  # Important: Use the NFS provisioner
parameters:
  server: nas5  # Or the IP address: 192.168.0.x
  path: /share
  # Optional parameters (adjust as needed)
  # readOnly: "false" 
  # nfsvers: "4.1"