apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-readarr-config-specific-pv # Specific PV for Readarr config subdirectory
  labels:
    type: nfs
    app: readarr-config # Differentiating label
spec:
  capacity:
    storage: 5Gi # Adjust as needed, can be smaller for just one app's config
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas5 # Your NFS server
    path: /share/configs/readarr # Points directly to the readarr subdirectory
    readOnly: false