apiVersion: v2
name: readarr-wrapper
description: A wrapper Helm chart to deploy Readarr using the media-servarr/readarr chart.
type: application

version: 0.1.0
appVersion: "nightly-0.4.17.2795-ls397" # Matches the appVersion of the chosen dependency chart

dependencies:
  - name: readarr # The name of the chart in the repository
    version: "10.0.17"
    repository: "https://charts.truecharts.org/"
    alias: readarr-dependency # An alias to make the Values.yaml clearer