replicaCount: 1

image:
  repository: linuxserver/couchpotato
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5050

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
  hosts:
    - host: "couchpotato.neilwylie.com" # Hostname
      paths:
        - path: "/"                     # Path to match
          pathType: Prefix              # PathType must be specified
  tls:
    - hosts:
        - couchpotato.neilwylie.com     # This hostname MUST match one in the hosts.host section above
      secretName: couchpotato-tls-secret # This is the name of the Kubernetes Secret cert-manager will create

puid: "1003"
pgid: "1003"

persistentVolumeClaims:
  config: nfs-configs-pvc
  downloads: nfs-temp-pvc
  movies: nfs-films-pvc

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
