replicaCount: 1

image:
  repository: linuxserver/couchpotato
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5050

ingress:
  enabled: true
  className: "nginx"
  host: "couchpotato.neilwylie.com"
  path: "/"
  tlsSecretName: couchpotato-tls

puid: "1003"
pgid: "1003"

persistentVolumeClaims:
  config: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "config") }}
  downloads: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "downloads") }}
  movies: {{ include "couchpotato.pvcName" (dict "Values" .Values "Release" .Release "pvcSuffix" "movies") }}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
