replicaCount: 1

image:
  repository: linuxserver/couchpotato
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5050

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
hosts:
    - host: "couchpotato.neilwylie.com" # Hostname
      paths:                            # List of paths for this host
        - path: "/"                    
tls:
    - hosts:
        # This hostname MUST match one in the hosts.host section above
        - couchpotato.neilwylie.com 
      # This is the name of the Kubernetes Secret cert-manager will create
      # and the Ingress controller will use.
      secretName: couchpotato-tls-secret # You can choose this name

puid: "1003"
pgid: "1003"

persistentVolumeClaims:
  config: nfs-configs-pvc
  downloads: nfs-temp-pvc
  movies: nfs-films-pvc

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
