image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

containerName: sonarr

persistence:
  config:
    enabled: true
    existingClaim: nfs-configs-pvc
    mountPath: /config #moving back 
    subPath: sonarr
  tv:
    enabled: true
    existingClaim: nfs-tv-pvc
    mountPath: /tv
  downloads:
    enabled: true
    existingClaim: nfs-temp-pvc
    mountPath: /downloads

localtime:
  hostPath: /etc/localtime
  mountPath: /etc/localtime
  readOnly: true

ports:
  http:
    containerPort: 8989
    servicePort: 8989

environment:
  PUID: "1003"
  PGID: "1003"

restartPolicy: Always

ingress:
  enabled: true
  className: "nginx" 
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
  hosts:
    - host: sonarr.neilwylie.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        # This hostname MUST match one in the hosts.host section above
        - sonarr.neilwylie.com 
      # This is the name of the Kubernetes Secret cert-manager will create
      # and the Ingress controller will use.
      secretName: sonarr-tls-secret # You can choose this name

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

replicaCount: 1 # Added for replica management

service:
  name: sonarr
  type: ClusterIP
  port: 8989