image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

containerName: sonarr

persistence:
  config:
    enabled: true
    existingClaim: nfs-configs-pvc
    mountPath: /config
    subPath: sonarr
  tv:
    enabled: true
    existingClaim: nfs-tv-pvc
    mountPath: /tv
  downloads:
    enabled: true
    existingClaim: nfs-temp-pvc
    mountPath: /downloads

ports:
  http:
    containerPort: 8989
    servicePort: 8989


restartPolicy: unless-stopped

ingress:
  enabled: true
  className: "nginx" # Or your ingress controller class
  hosts:
    - host: sonarr.neilwylie.com
      paths:
        - path: /
          pathType: Prefix
  tls: [] # Leave empty unless you have TLS certificates

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
