all:
  children:
    workstations:
      hosts:
        sabretooth:
        thinkpad:
    nas:
      hosts:
        nas2:
        nas3:
        nas4:
    Pi:
      hosts:
        node1:
        node2:
        node3:
