---

- hosts: all
  become: true
  roles:
  - role: update
  - role: common
  - role: monitoring


- hosts: workstations
  roles:
  - role: workstations
  - role: tailscale

- hosts: nuc_cluster
  become: true
  vars:
    ansible_user: neil
  roles:
    - microk8s
    - tailscale

# - hosts: turing
#   roles:
#   - role: turing