---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  roles:
  - role: common

- hosts: nas
  roles:
  - role: nas

- hosts: nas3
  roles:
  - role: dnsmasq
