---

- hosts: all
  become: true
  roles:
  - role: update
  - role: common
  - role: geerlingguy.node_exporter

- hosts: workstations
  roles:
  - role: workstations 

# - hosts: turing
#   roles:
#   - role: turing