---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  roles:
  - role: common

- hosts: nas
  roles:
  - role: nas
    
- import_playbook: dhcp.yml
- import_playbook: bind.yml
