---
# tasks file for update

- name: Update package lists
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: Autoremove unused dependencies
  apt:
    autoremove: yes