---
# tasks file for update

- name: Update package lists
  apt:
    update_cache: yes
  become: true
  ignore_errors: true
  retries: 5
  delay: 10
  register: update_result
  until: update_result is succeeded

- name: Upgrade all packages
  apt:
    upgrade: dist
  become: true
  ignore_errors: true
  retries: 5
  delay: 10
  register: upgrade_result
  until: upgrade_result is succeeded

- name: Autoremove unused dependencies
  apt:
    autoremove: yes
  become: true
  retries: 5
  delay: 10
  register: autoremove_result
  until: autoremove_result is succeeded