---
# tasks file for update

- name: Update package lists
  block:
    - apt:
        update_cache: yes
      become: true
      ignore_errors: true

- name: Upgrade all packages
  block:
    - apt:
        upgrade: yes
      become: true
      ignore_errors: true

- name: Autoremove unused dependencies
  block:
    - apt:
        autoremove: yes
      become: true