apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzb.fullname" . }}
  labels:
    {{- include "sabnzb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: web
    - port: 8085
      targetPort: 8085
      name: https
    - port: 9090
      targetPort: 9090
      name: api
    - port: 9095
      targetPort: 9095
      name: https-api
  selector:
    {{- include "sabnzb.selectorLabels" . | nindent 4 }}