apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr # Name of this child application in ArgoCD
  namespace: argocd # This Application CR itself lives in 'argocd'
  labels:
    app-group: media-stack # For grouping/filtering
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Neilrw86/Nas-Automation
    targetRevision: June
    path: helm_charts/sonarr # Path to your Sonarr wrapper Helm chart
    helm:
      valueFiles:
        - values.yaml # Uses values.yaml from helm_charts/sonarr/

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Sonarr's resources will be deployed into the 'default' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true