name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' 

    - name: Install Ansible and dependencies
      run: |
        pip install ansible ansible-lint yamllint

    - name: Lint Playbooks
      run: ansible-lint ./Ansible
      continue-on-error: true

    - name: Validate YAML Syntax
      run: yamllint ./Ansible
      continue-on-error: true
