name: Generate Badge

on:
  workflow_run:
    workflows: ["Deploy with Ansible"]
    types:
      - completed

jobs:
  badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Generate Badge
        run: |
          # Your badge generation script here