name: Publish Helm Charts

on:
  pull_request:
    branches:
      - main
    paths:
      - 'helm_charts/**' # Only trigger on changes to the helm charts folder

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Helm
        uses: azure/setup-helm@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Charts
        run: |
          for chart in ./helm_charts/*; do
            chart_name=$(basename "$chart")
            helm package "$chart"
            helm push "$chart_name-*.tgz" oci://ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          done
