name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - v*

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}