name: Lint & apply

on:
  push:
    branches:
      - main  # Or your preferred deployment branch
  workflow_dispatch:  # Allows manual triggering

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: self-hosted # Make sure this runner has sudo access
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or the version Ansible needs

      - name: Deploy with Ansible (using sudo and password)
        run: |
          cd Ansible/; echo "${{ secrets.SUDO_PASSWORD }}" | ansible-playbook -i inventory.yml site.yml
