name: Ansible site.yml apply - self-hosted runner

on:
  push:
    branches:
      - main  # Or your preferred deployment branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  apply:
    runs-on: self-hosted # Make sure this runner has sudo access

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or the version Ansible needs

      - name: Deploy with Ansible, runs on desktop.neilwylie.com
        if: always()
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
        run: |
          cd Ansible/; ansible-playbook -i inventory.yml site.yml
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ] || [ $EXIT_CODE -eq 4 ]; then
            exit $EXIT_CODE
          else
            exit 0
          fi

