name: Lint & Apply

on:
  push:
    branches:
      - main  # Or your preferred deployment branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' 

      - name: Install Ansible and dependencies
        run: |
          pip install ansible ansible-lint yamllint

      - name: Lint Playbooks
        run: ansible-lint ./Ansible
        continue-on-error: true

      - name: Validate YAML Syntax
        run: yamllint ./Ansible
        continue-on-error: true

  deploy:
    runs-on: self-hosted # Make sure this runner has sudo access
    needs: lint  # This ensures the deploy job runs only if the lint job passes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or the version Ansible needs

      - name: Deploy with Ansible, runs on desktop.neilwylie.com
        if: always()
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
        run: |
          cd Ansible/; ansible-playbook -i inventory.yml site.yml
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ] || [ $EXIT_CODE -eq 4 ]; then
            exit $EXIT_CODE
          else
            exit 0
          fi

