name: Lint & apply + Badge
on:
  push:
    branches:
      - main  # Or your preferred deployment branch
  workflow_dispatch:  # Allows manual triggering

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: self-hosted # Make sure this runner has sudo access
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or the version Ansible needs

      - name: Deploy with Ansible , runs on desktop.neilwylie.com
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
        run: |
          cd Ansible/; ansible-playbook -i inventory.yml site.yml
                    EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ] || [ $EXIT_CODE -eq 4 ]; then
            exit $EXIT_CODE
          else
            exit 0
          fi

  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          gistID: ee109f3ae7277a150b455d37f14f6355
          filename: test.json # Use test.svg if you want to use the SVG mode.
          label: Last GitHub Actions Run
          message: ${{ steps.get_status.outputs.status }}
          color: ${{ steps.get_status.outputs.status == 'success' && 'green' || 'red' }}

      - name: Upload badge artifact
        uses: actions/upload-artifact@v3
        with:
          name: badge
          path: badge.svg