name: prettier
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        run: prettier --write .

      - name: Commit changes
        id: commit-changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="lint-fixes-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Apply lint fixes"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-changes.outputs.BRANCH_NAME }}
          base: main
          title: "Automated PR: Apply lint fixes"
          body: "This PR was created automatically by GitHub Actions to apply lint fixes."