name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Extract container images from Helm charts
        id: extract-images
        run: |
          images=""
          for chart in ./helm_charts/*; do
            images="$images $(helm template "$chart" | grep 'image:' | awk '{print $2}')"
          done
          images=$(echo "$images" | xargs) # Remove extra spaces
          echo "IMAGES=$images" >> $GITHUB_ENV

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGES }}