name: Trivy Scan

on:
push:
    branches:
        - '**'
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Extract container images from Helm charts
        id: extract-images
        run: |
          images=$(helm template ./helm_charts/* | grep 'image:' | awk '{print $2}')
          echo "::set-output name=images::$images"

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.extract-images.outputs.images }}