name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Extract container images from Helm charts
        id: extract-images
        run: |
          for chart in ./helm_charts/*; do
            # Extract image references from Helm templates
            helm template "$chart" | grep 'image:' | awk '{print $2}' >> images.txt
          done
          # Remove duplicates and empty lines
          sort -u images.txt | sed '/^$/d' > unique-images.txt

      - name: Run Trivy scan for each image
        run: |
          while IFS= read -r image; do
            echo "Scanning image: $image"
            trivy image "$image"
          done < unique-images.txt