name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2 # Specify a recent Helm version

      - name: Install Trivy CLI
        uses: aquasecurity/trivy-action@master

      - name: Install helm-trivy plugin
        run: |
          export GIT_TERMINAL_PROMPT=0
          helm plugin install https://github.com/aquasecurity/helm-trivy
          helm plugin list # Verify plugin installation
        shell: bash

      - name: Scan Helm charts with helm-trivy
        run: |
          set -eo pipefail # Exit on error, treat unset variables as an error, and pipefail

          # Find all directories directly under helm_charts, assuming each is a chart
          CHART_DIRECTORIES=$(find ./helm_charts -mindepth 1 -maxdepth 1 -type d)

          if [ -z "$CHART_DIRECTORIES" ]; then
            echo "No chart directories found under ./helm_charts/"
            exit 0
          fi

          for chart_dir in $CHART_DIRECTORIES; do
            echo "--------------------------------------------------"
            echo "Scanning chart directory: $chart_dir with helm-trivy"
            echo "--------------------------------------------------"
            # Run helm trivy on the chart directory
            # Adjust Trivy flags as needed.
            # --skip-dirs can be used if you have sub-charts you don't want to scan individually,
            # but helm-trivy should generally handle dependencies correctly.
            helm trivy "$chart_dir" \
              --exit-code 0 \
              --format table \
              --ignore-unfixed \
              --vuln-type os,library \
              --severity CRITICAL,HIGH \
              --exit-on-policy-failure
          done
        shell: bash
