global: {}

controller:
  main:
    type: deployment

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext:
  runAsUser: 1003
  runAsGroup: 1003

service:
  main:
    ports:
      main:
        port: 7878

ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-cfdns
    hosts:
      - host: "radarr.neilwylie.com"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "radarr.neilwylie.com"
        secretName: "radarr-tls-secret"

persistence:
  config:
    enabled: true
    existingClaim: nfs-configs-pvc
  downloads:
    enabled: true
    existingClaim: nfs-temp-pvc
    mountPath: /downloads
  movies:
    enabled: true
    existingClaim: nfs-films-pvc
    mountPath: /movies
